
name: batur_chat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  encrypt: ^5.0.1
  flutter_riverpod: ^2.5.1
  lottie: ^3.0.0
  emoji_picker_flutter: ^2.2.0
  cached_network_image: ^3.3.0
  image_picker: ^1.1.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter_native_splash:
  color: "#1E88E5"
  image: assets/icons/ic_launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
